config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> user { user.admin? } do
    mount Delayed::Web::Engine, at: '/jobs'
  end
  get 'auth/:provider/callback', to: 'connections#create'
  resources :connections, only: [:destroy]
  get 'auth/failure', to: 'connections#omniauth_failure'


  devise_for :users, controllers: { registrations: 'registrations'}
  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user

  def self.create_from_omniauth(auth_hash)
    create(
        provider: auth_hash.provider,
        oauth_token: auth_hash.credentials.token,
        secret: auth_hash.credentials.secret
    )
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :content
  validates_presence_of :scheduled_at
  validates_length_of :content, maximum: 140, message: 'Less then 140 characters please'
  after_create :schedule

  def schedule
    begin
      ScheduleJob.set(wait_until: scheduled_at).perform_later(self)
      self.update_attributes(state: "scheduled")
    rescue Exception => e
      self.update_attributes(state: "scheduled error", error: e.message)
    end
  end

  def display
    begin
      if twitter == true
        to_twitter
      end
      if facebook == true
        to_facebook
      end
      if linkedin == true
        to_linkedin
      end
      self.update_attributes(state: "posted")
    rescue Exception => e
      self.update_attributes(state: "posting error", error: e.message)
    end
  end

  def to_twitter
    client = Twitter::REST::Client.new do |config|
      config.access_token = self.user.twitter.oauth_token
      config.access_token_secret = self.user.twitter.secret
      config.consumer_key = ENV["TWITTER_KEY"]
      config.consumer_secret = ENV["TWITTER_SECRET"]
    end
    client.update(self.content)
  end

  def to_facebook
    graph = Koala::Facebook::API.new(self.user.facebook.oauth_token)
    graph.put_connections("me", "feed", message: self.content)
  end

  def to_linkedin
    api = LinkedIn::API.new(self.user.linkedin.oauth_token)
    api.add_share(comment: self.content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :time_zone
  has_many :connections, dependent: :destroy
  has_many :posts, dependent: :destroy

  def twitter
    self.connections.where(provider: 'twitter').first
  end

  def facebook
    self.connections.where(provider: 'facebook').first
  end

  def linkedin
    self.connections.where(provider: 'linkedin').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  around_action :user_time_zone, if: :current_user

  private

  def user_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:destroy]

  def create
    connection = current_user.connections.create_from_omniauth(auth_hash)
    if connection.save
      redirect_to dashboard_path, notice: "Connection Created!"
    else
      redirect_to dashboard_path, notice: "Something went wrong!"
    end
  end

  def destroy
    @connection.destroy
    redirect_to dashboard_path, notice: "Connection Deleted"
  end

  def omniauth_failure
    redirect_to dashboard_path, notice: "Something went wrong!"
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def set_connection
    @connection = Connection.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
    if current_user
      redirect_to dashboard_path
    end
  end

  def dashboard
    @scheduled = current_user.posts.where(state: "scheduled").order("scheduled_at ASC")
    @history = current_user.posts.where.not(state:"scheduled").order("scheduled_at DESC")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    if current_user.connections.any?
      @post = Post.new
    else
      redirect_to dashboard_path, notice: "Please create a connection first!"
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to dashboard_path, notice: "Post successfully created!"}
      else
        format.html { render :new }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :scheduled_at, :state, :user_id, :facebook, :twitter, :linkedin)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :time_zone)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :time_zone, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Varios", root_path, class: "navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if current_user%>
          <li><%= link_to "New post", new_post_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Jobs", '/jobs' %></li>
          <%end%>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign in", new_user_registration_path %></li>
        <%end%>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Varios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
  </head>

  <%= render 'layouts/header' %>

  <body class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">

  <!-- settings and connections -->
  <div class="col-md-4 text-center">
    <h3 class="text-center">Connections</h3>
    <hr>
    <%= image_tag 'Varios2.png', class: 'logo' %>
    <div class="time-zone">
      <p class="text-center">
        <b><%= Time.zone.name %> Timezone </b>
        <%= link_to 'change', edit_user_registration_path %>
      </p>
      <div class="social">
        <% unless current_user.connections.where(provider: 'twitter').any? %>
            <%= link_to 'Connect Twitter', 'auth/twitter', class: 'btn btn-info btn-block btn-sm' %>
        <% else %>
            <%= link_to 'Connect Twitter', 'auth/twitter', class: 'btn btn-info btn-block btn-sm', disabled: true %>
            <%= link_to 'Delete Connection', connection_path(current_user.connections.where(provider: 'twitter').first), method: :delete %>
        <% end %>

        <% unless current_user.connections.where(provider: 'facebook').any? %>
            <%= link_to 'Connect Facebook', 'auth/facebook', class: 'btn btn-primary btn-block btn-sm' %>
        <% else %>
            <%= link_to 'Connect Facebook', 'auth/facebook', class: 'btn btn-primary btn-block btn-sm', disabled: true %>
            <%= link_to 'Delete Connection', connection_path(current_user.connections.where(provider: 'facebook').first), method: :delete %>
        <% end %>

        <% unless current_user.connections.where(provider: 'linkedin').any? %>
            <%= link_to 'Connect LinkedIn', 'auth/linkedin', class: 'btn btn-primary btn-block btn-sm' %>
        <% else %>
            <%= link_to 'Connect LinkedIn', 'auth/linkedin', class: 'btn btn-primary btn-block btn-sm', disabled: true %>
            <%= link_to 'Delete Connection', connection_path(current_user.connections.where(provider: 'linkedin').first), method: :delete %>
        <% end %>
      </div>
    </div>

    <div class="social">
    </div>

  </div>

  <!-- scheduled posts -->
  <div class="col-md-4">
    <h3 class="text-center">Scheduled</h3>
    <hr>
    <%= render @scheduled %>
  </div>

  <!-- post history	 -->
  <div class="col-md-4">
    <h3 class="text-center">History</h3>
    <hr>
    <%= render @history %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-3">I'm Varios!</h1>
  <p class="lead">Varios is a simpler and easier way to schedule posts, and manage all your accounts in one place</p>
    <%= link_to 'Sign in for free', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f|  %>
    <%= f.error_notification %>

    <div class="form-input">
      <%= f.input :content, required: true, maxlength: 140 %>
      <p>This post will be scheduled in <b><%= Time.zone.name %></b></p>
      <%= f.input :scheduled_at, required: true %>
    </div>

    <div class="form-input">
      <% if current_user.connections.where(provider: 'twitter').any? %>
          <%= f.input :twitter %>
      <% end %>
      <% if current_user.connections.where(provider: 'facebook').any? %>
          <%= f.input :facebook %>
      <% end %>
      <% if current_user.connections.where(provider: 'linkedin').any? %>
          <%= f.input :linkedin %>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>

<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <!-- heading -->
  <div class="panel-heading">
    <% if post.facebook == true %> <span class="label label-primary">Facebook</span> <% end %>
    <% if post.twitter == true %> <span class="label label-info">Twitter</span> <% end %>
    <% if post.linkedin == true %> <span class="label label-primary">LinkedIn</span> <% end %>
    Scheduled on <%= post.scheduled_at %>
  </div>
  <!-- body -->
  <div class="panel-body">
    <%= post.content %>
  </div>
  <div class="panel-footer">
    <p><%= post.state.capitalize %></p>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "back", dashboard_path %>